# Generated by Django 3.0.3 on 2020-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
